const ROLES = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  MERCHANT: 'MERCHANT',
  CUSTOMER: 'CUSTOMER'
};

const ADMIN_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN'
};

const ONBOARDING_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  BLOCKED: 'BLOCKED'
};

const ONBOARDING_STEP_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED'
};

const TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

const TICKET_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

const TICKET_SOURCE = {
  CHATBOT: 'CHATBOT',
  EMAIL: 'EMAIL',
  PORTAL: 'PORTAL',
  ADMIN: 'ADMIN'
};

const SUPPORT_CHANNEL = {
  PHONE: 'PHONE',
  VIDEO: 'VIDEO',
  EMAIL: 'EMAIL',
  CHAT: 'CHAT',
  OTHER: 'OTHER'
};

const COMMUNICATION_CHANNEL = {
  EMAIL: 'EMAIL',
  CHAT: 'CHAT',
  PHONE: 'PHONE',
  VIDEO: 'VIDEO',
  OTHER: 'OTHER'
};

const COMMUNICATION_DIRECTION = {
  INBOUND: 'INBOUND',
  OUTBOUND: 'OUTBOUND'
};

const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const FULFILLMENT_STATUS = {
  UNFULFILLED: 'UNFULFILLED',
  FULFILLED: 'FULFILLED',
  SHIPPED: 'SHIPPED',
  DELIVERED: 'DELIVERED'
};

module.exports = {
  ROLES,
  ADMIN_ROLES,
  ONBOARDING_STATUS,
  ONBOARDING_STEP_STATUS,
  TICKET_STATUS,
  TICKET_PRIORITY,
  TICKET_SOURCE,
  SUPPORT_CHANNEL,
  COMMUNICATION_CHANNEL,
  COMMUNICATION_DIRECTION,
  ORDER_STATUS,
  PAYMENT_STATUS,
  FULFILLMENT_STATUS
};
